MvcAppVs2013/Models/City.cs
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace MvcAppVs2013.Models
{
    public class City
    {
        public long Id { get; set; }
        //[IsCityAlreadyexist(ErrorMessage = "City Already Exists.")]
        [Display(Name = "City Name")]
       // [Required]
        [IsCityAlreadyexist(ErrorMessage = "City Already Exists.")]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Alphabets Please.")]
        public string Name { get; set; }
        public double Review { get; set; }
        public bool IsActive { get; set; }
       // public State state { get; set; }
    }

    public class State
    {
        public int Code { get; set; }
    }
    #region Data Annotations

    //[Required(ErrorMessage = "Hey, you missed the code.")]
    //[RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Alphabets Please.")]
     //[DisplayFormat(NullDisplayText = "Anonymous")]


    //[Display(Name = "City Name")]

    //[IsCityAlreadyexist(ErrorMessage = "City Already Exists.")]
    //[Range(1,999)]

    public class IsCityAlreadyexist : ValidationAttribute
    {

        protected override ValidationResult IsValid(object value,ValidationContext validationContext)
        {
            var cityName = value;
            if (cityName.ToString().ToLower() != "")
            {
                var stubbedCityProvider = new StubbedCityProvider();
                if (stubbedCityProvider.InSessionCities.Any(a => a.Name.ToLower().Trim() == cityName.ToString().Trim().ToLower() ))
                {
                    return new ValidationResult(FormatErrorMessage(validationContext.DisplayName));
                }
                else
                {
                    return ValidationResult.Success;
                }
            }
            return ValidationResult.Success;
        }
    }
    #endregion
}

MvcAppVs2013/Controllers/CityController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using MvcAppVs2013.Filters;
using MvcAppVs2013.Models;

namespace MvcAppVs2013.Controllers
{
    [Log]
    public class CityController : Controller
    {
        public StubbedCityProvider cityStub
        {
            get { return new StubbedCityProvider(); }
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View(cityStub.InSessionCities);
        }

        [HttpGet]
        public IEnumerable<City> GetCities()
        {
            var cities = new List<City>
            {
                new City() {Id = 1, IsActive = true, Name = "Pune", Review = 9.9},
                new City() {Id = 2, IsActive = true, Name = "Delhi", Review = 5.9}
            };
            return cities;
        }

        [HttpGet]
        public JsonResult GetCitiesJson()
        {
            var cities = new List<City>
            {
                new City() {Id = 1, IsActive = true, Name = "Pune", Review = 9.9},
                new City() {Id = 2, IsActive = true, Name = "Delhi", Review = 5.9}
            };
            return Json(new
            {
                city = cities
            },JsonRequestBehavior.AllowGet);
        }


        [HttpGet]
        public ActionResult Create()
        {
            return View(new City(){ });
        }

        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(City city)
        {
            if (ModelState.IsValid)
            {
                cityStub.Add(city);
                return RedirectToAction("Index");
            }
            return View();
        }


        [HttpPost]
        public ActionResult Create(City city)
        {
            if(ModelState.IsValid)
            {
                cityStub.Add(city);
                return RedirectToAction("Index");                  
            }
            return View();
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var city = cityStub.InSessionCities.First(a => a.Id == id);
            return View(city);
        }

        [HttpPost]
        public ActionResult Edit(City city)
        {
            if (ModelState.IsValid)
            {
                cityStub.Update(city);
                return RedirectToAction("Index");
            }
            return View();
        }
    }


     
  
}

MvcAppVs2013/Views/City/Add.cshtml
<h2>Add</h2>
<form method="post" action="/City/Add" >
    @Html.AntiForgeryToken()
    <div class="editor-label">
        <label for="Name">Name</label>
    </div>
    <div class="editor-field">
        <input class="text-box single-line" id="Name" name="Name" type="text" value="" />
         <input class="text-box single-line" id="Name" name="state.Code" type="text" value="" />
        <span class="field-validation-valid" data-valmsg-for="Name" data-valmsg-replace="true"></span>
    </div>

    <div class="editor-label">
        <label for="Review">Review</label>
    </div>
    <div class="editor-field">
        <input class="text-box single-line" data-val="true" data-val-number="The field Review must be a number." data-val-required="The Review field is required." id="Review" name="Review" type="text" value="" />
        <span class="field-validation-valid" data-valmsg-for="Review" data-valmsg-replace="true"></span>
    </div>

    <div class="editor-label">
        <label for="IsActive">IsActive</label>
    </div>
    <div class="editor-field">
        <input class="check-box" data-val="true" data-val-required="The IsActive field is required." id="IsActive" name="IsActive" type="checkbox" value="true" /><input name="IsActive" type="hidden" value="false" />
        <span class="field-validation-valid" data-valmsg-for="IsActive" data-valmsg-replace="true"></span>
    </div>
    <p>
        <input type="submit" value="Create" />
    </p>
</form>

<script src="/Scripts/jquery.unobtrusive-ajax.js"></script>
<script src="/Scripts/jquery.validate.js"></script>
<script src="/Scripts/jquery.validate.unobtrusive.js"></script>

<div>
    <a href="/City">Back to List</a>
</div>

MvcAppVs2013/Views/City/Create.cshtml
@model MvcAppVs2013.Models.City

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>City</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name )
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Review)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Review)
            @Html.ValidationMessageFor(model => model.Review)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.IsActive)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.IsActive)
            @Html.ValidationMessageFor(model => model.IsActive)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcAppVs2013/Views/City/Edit.cshtml
@model MvcAppVs2013.Models.City

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit","City"))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>City</legend>

        @Html.HiddenFor(model => model.Id)

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Review)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Review)
            @Html.ValidationMessageFor(model => model.Review)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.IsActive)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.IsActive)
            @Html.ValidationMessageFor(model => model.IsActive)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcAppVs2013/Views/City/Index.cshtml
@model IEnumerable<MvcAppVs2013.Models.City>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
    
      @Html.ActionLink("Create New with Html", "Add")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Review)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsActive)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Review)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsActive)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>